[build]
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_KEY,SESSION_SECRET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200